// Static suggestion lists for the Profile combobox fields (Location, School).
// Bundled on purpose: no external Places/Schools API to depend on or key. The
// fields stay free-text, these only power the type-to-filter dropdown, so
// anything not listed can still be typed in.

export const CITY_SUGGESTIONS: string[] = [
  // United States (largest cities + notable college towns), "City, ST"
  "New York, NY","Los Angeles, CA","Chicago, IL","Houston, TX","Phoenix, AZ",
  "Philadelphia, PA","San Antonio, TX","San Diego, CA","Dallas, TX","San Jose, CA",
  "Austin, TX","Jacksonville, FL","Fort Worth, TX","Columbus, OH","Charlotte, NC",
  "San Francisco, CA","Indianapolis, IN","Seattle, WA","Denver, CO","Washington, DC",
  "Boston, MA","Nashville, TN","Detroit, MI","Oklahoma City, OK","Portland, OR",
  "Las Vegas, NV","Memphis, TN","Louisville, KY","Baltimore, MD","Milwaukee, WI",
  "Albuquerque, NM","Tucson, AZ","Fresno, CA","Sacramento, CA","Kansas City, MO",
  "Mesa, AZ","Atlanta, GA","Omaha, NE","Colorado Springs, CO","Raleigh, NC",
  "Long Beach, CA","Virginia Beach, VA","Miami, FL","Oakland, CA","Minneapolis, MN",
  "Tulsa, OK","Bakersfield, CA","Wichita, KS","Arlington, TX","Aurora, CO",
  "Tampa, FL","New Orleans, LA","Cleveland, OH","Honolulu, HI","Anaheim, CA",
  "Lexington, KY","Stockton, CA","Corpus Christi, TX","Henderson, NV","Riverside, CA",
  "Newark, NJ","Saint Paul, MN","Santa Ana, CA","Cincinnati, OH","Irvine, CA",
  "Orlando, FL","Pittsburgh, PA","St. Louis, MO","Greensboro, NC","Jersey City, NJ",
  "Anchorage, AK","Lincoln, NE","Plano, TX","Durham, NC","Buffalo, NY",
  "Chandler, AZ","Madison, WI","Reno, NV","Boise, ID","Fremont, CA",
  "Spokane, WA","Baton Rouge, LA","Richmond, VA","Tacoma, WA","Salt Lake City, UT",
  "Grand Rapids, MI","Huntsville, AL","Des Moines, IA","Rochester, NY","Birmingham, AL",
  "Providence, RI","Knoxville, TN","Charleston, SC","Savannah, GA","Fort Lauderdale, FL",
  "Chattanooga, TN","Tempe, AZ","Scottsdale, AZ","Eugene, OR","Fort Collins, CO",
  "Springfield, MO","Alexandria, VA","Bellevue, WA","Naperville, IL","Bridgeport, CT",
  "Savannah, GA","Syracuse, NY","Gainesville, FL","Waco, TX","Dayton, OH",
  "Columbia, SC","Cedar Rapids, IA","Stamford, CT","New Haven, CT","Columbia, MO",
  "Fargo, ND","Topeka, KS","Allentown, PA","Hartford, CT","College Station, TX",
  "Wilmington, NC","Berkeley, CA","Cambridge, MA","Palo Alto, CA","Ann Arbor, MI",
  "Boulder, CO","Athens, GA","Chapel Hill, NC","Princeton, NJ","New Brunswick, NJ",
  "Ithaca, NY","Evanston, IL","Bloomington, IN","Champaign, IL","Gainesville, GA",
  "Provo, UT","Santa Barbara, CA","Santa Cruz, CA","Pasadena, CA","Tallahassee, FL",
  "Iowa City, IA","Norman, OK","Lawrence, KS","Columbus, GA","Burlington, VT",
  "Portland, ME","Manchester, NH","Wilmington, DE","Boise, ID","Missoula, MT",
  "Bozeman, MT","Sioux Falls, SD","Cheyenne, WY","Fayetteville, AR","Jackson, MS",
  // International, "City, Country"
  "London, UK","Manchester, UK","Edinburgh, UK","Toronto, Canada","Vancouver, Canada",
  "Montreal, Canada","Ottawa, Canada","Calgary, Canada","Paris, France","Lyon, France",
  "Berlin, Germany","Munich, Germany","Hamburg, Germany","Amsterdam, Netherlands",
  "Dublin, Ireland","Madrid, Spain","Barcelona, Spain","Rome, Italy","Milan, Italy",
  "Zurich, Switzerland","Geneva, Switzerland","Stockholm, Sweden","Oslo, Norway",
  "Copenhagen, Denmark","Helsinki, Finland","Lisbon, Portugal","Vienna, Austria",
  "Brussels, Belgium","Warsaw, Poland","Prague, Czechia","Sydney, Australia",
  "Melbourne, Australia","Brisbane, Australia","Perth, Australia","Auckland, New Zealand",
  "Tokyo, Japan","Osaka, Japan","Singapore","Hong Kong","Seoul, South Korea",
  "Mumbai, India","Bangalore, India","Delhi, India","Hyderabad, India","Dubai, UAE",
  "Abu Dhabi, UAE","Tel Aviv, Israel","Mexico City, Mexico","Guadalajara, Mexico",
  "São Paulo, Brazil","Rio de Janeiro, Brazil","Buenos Aires, Argentina","Santiago, Chile",
  "Bogotá, Colombia","Cape Town, South Africa","Johannesburg, South Africa","Nairobi, Kenya",
];

export const SCHOOL_SUGGESTIONS: string[] = [
  // US universities + liberal arts colleges
  "Harvard University","Stanford University","Massachusetts Institute of Technology",
  "Yale University","Princeton University","Columbia University","University of Pennsylvania",
  "Cornell University","Brown University","Dartmouth College","University of Chicago",
  "Duke University","Northwestern University","Johns Hopkins University","California Institute of Technology",
  "University of California, Berkeley","University of California, Los Angeles",
  "University of California, San Diego","University of California, Davis",
  "University of California, Irvine","University of California, Santa Barbara",
  "University of Southern California","New York University","Boston University","Boston College",
  "Georgetown University","University of Michigan","University of Virginia",
  "University of North Carolina at Chapel Hill","Georgia Institute of Technology",
  "University of Texas at Austin","Texas A&M University","University of Florida",
  "University of Washington","University of Wisconsin, Madison",
  "University of Illinois Urbana-Champaign","Ohio State University","Pennsylvania State University",
  "Purdue University","Indiana University","Michigan State University","University of Minnesota",
  "University of Maryland","Rutgers University","University of Notre Dame","Vanderbilt University",
  "Rice University","Emory University","Carnegie Mellon University","Washington University in St. Louis",
  "Tufts University","Wake Forest University","Case Western Reserve University","University of Rochester",
  "Northeastern University","University of Miami","Syracuse University","Arizona State University",
  "University of Arizona","University of Colorado Boulder","University of Oregon","University of Georgia",
  "University of Tennessee","University of Kentucky","University of Alabama","Auburn University",
  "Louisiana State University","University of Iowa","University of Kansas","University of Missouri",
  "University of Nebraska","University of Utah","University of Pittsburgh","Virginia Tech",
  "Clemson University","Florida State University","University of South Carolina",
  "University of Connecticut","University of Massachusetts Amherst","University of Vermont",
  "University of New Hampshire","Baylor University","Southern Methodist University",
  "Texas Christian University","Villanova University","Fordham University","Pepperdine University",
  "Santa Clara University","Loyola Marymount University","DePaul University","Marquette University",
  "George Washington University","American University","Howard University","Spelman College",
  "Morehouse College","Williams College","Amherst College","Swarthmore College","Wellesley College",
  "Bowdoin College","Middlebury College","Pomona College","Claremont McKenna College","Harvey Mudd College",
  "Colgate University","Hamilton College","Vassar College","Bates College","Colby College",
  "Oberlin College","Kenyon College","Reed College","Grinnell College","Davidson College",
  "Barnard College","Smith College","Mount Holyoke College","Wesleyan University","Bard College",
  "Sarah Lawrence College","Occidental College","Macalester College","Carleton College","Bucknell University",
  "Lehigh University","Rensselaer Polytechnic Institute","Worcester Polytechnic Institute",
  "Stevens Institute of Technology","Rochester Institute of Technology","Cal Poly San Luis Obispo",
  "San Diego State University","San Jose State University","University of Houston","University of Central Florida",
  "University of South Florida","Temple University","Drexel University","University of Delaware",
  "University of Cincinnati","University of Oklahoma","Oklahoma State University","Kansas State University",
  "Iowa State University","Colorado State University","Oregon State University","Washington State University",
  "University of Nevada, Las Vegas","University of Hawaii at Manoa",
  // International
  "University of Oxford","University of Cambridge","Imperial College London",
  "London School of Economics","University College London","King's College London",
  "University of Edinburgh","University of Manchester","University of Toronto","McGill University",
  "University of British Columbia","University of Waterloo","ETH Zurich","EPFL",
  "National University of Singapore","Nanyang Technological University","University of Melbourne",
  "University of Sydney","Australian National University","University of Tokyo","Kyoto University",
  "Tsinghua University","Peking University","Seoul National University","Trinity College Dublin",
  "Delft University of Technology","Technical University of Munich","Sciences Po","HEC Paris",
];
